### ISSUE TITLE
D65 illuminant question.

### ISSUE THREAD

**Issue by paolodep36** [sentinel-toolkit/sentinel-toolkit#10]
Hi, is there any way to not use the d65 standard and thus have the whole sentinel 2 spectrum when the ecospec library is converted?

Thank you

**Comment by gdgenchev** [comment]
Hello, that is a good question. It seems I have missed adding a way to configure the illuminant in the converter main script arguments. I think it will be an easy fix (as main already calls a method that accepts illuminant, but currently passes None) and in the end it will be easy to pass identity/d65/other illuminant as an argument. I will try to implement this today.

**Comment by paolodep36** [comment]
Cool! I wanted to use your library to convert ecospec values in sentinel response in the full spectrum. right now i can create a csv with all the bands, but from band 8 to Band 12 every values is equal to 0

**Comment by gdgenchev** [comment]
Hello, I think I implemented the requirement. Now you can use the -i identity (also supports d65) argument when running the convert script (also -if <illuminant_filename> can be used for custom illuminants) . Note that for this to work, you should also provide proper wavelength range (-ws and -we), so that it covers the range of all the spectral distribution examples in ecostress library. I hope this helps and I am looking forward to your feedback! Thank you!

**Comment by paolodep36** [comment]
can you provide an example on how to use identity parameter? Such as in this example. Thank you anyways
`from spectral import EcostressDatabase
from sentinel_toolkit.ecostress import Ecostress
from sentinel_toolkit.srf import S2Srf, S2SrfOptions
from sentinel_toolkit.colorimetry import sd_to_sentinel_numpy, sd_to_sentinel_direct_numpy
from sentinel_toolkit.colorimetry.illuminants import D65_360_830_1NM

ecostress_db = EcostressDatabase("ecostress.db")
ecostress = Ecostress(ecostress_db)
s2a_srf = S2Srf("srf.xlsx")

wavelength_range = (360, 830)

spectrum_id = 1
# Use the numpy version for better performance
spectral_data = ecostress.get_spectral_distribution_numpy(spectrum_id, wavelength_range)

spectral_data_min_wavelength = spectral_data.wavelengths[0]
spectral_data_max_wavelength = spectral_data.wavelengths[-1]

wr_start = max(wavelength_range[0], spectral_data_min_wavelength)
wr_end = min(wavelength_range[1], spectral_data_max_wavelength)

# You need to provide an illuminant, that at least covers the range of all the spectral distributions
# i.e. if your data contains values in (360, 830), then the illuminant should be in range (<= 360, >= 830)
# Otherwise, exception will be raised (currently no interpolation is performed on the illuminant)
illuminant = D65_360_830_1NM

# Get the sentinel responses for spectrum with id 1 for all bands
# from satellite 'A' in wavelength_range (360, 830)
s2_srf_options = S2SrfOptions(satellite='A', wavelength_range=(wr_start, wr_end))
sentinel_responses = sd_to_sentinel_numpy(spectral_data,
                                          s2a_srf,
                                          s2_srf_options,
                                          illuminant)

# Another way of doing this would be:
s2_srf_options = S2SrfOptions(satellite='A', wavelength_range=(wr_start, wr_end))
bands_responses = s2a_srf.get_bands_responses(s2_srf_options)
sentinel_responses = sd_to_sentinel_direct_numpy(spectral_data, bands_responses, illuminant)`

**Comment by gdgenchev** [comment]
You can either use the main script like for example:
```
python converter.py -e ecostress.db -s2 S2-SRF_COPE-GSEG-EOPG-TN-15-0007_3.0.xlsx -s A  -ws 360 -we 2000 -i identity
```
or you can do it programatically like:
```
from sentinel_toolkit.colorimetry import get_well_known_illuminant

ecostress_db = EcostressDatabase("ecostress.db")
ecostress = Ecostress(ecostress_db)
s2a_srf = S2Srf("srf.xlsx")
converter = EcostressToSentinelConverter(ecostress, s2a_srf)

wavelength_range=(360, 2000)
s2_srf_options = S2SrfOptions(satellite='A',  wavelength_range)
illuminant = get_well_known_illuminant('identity', wavelength_range)
converter.convert_ecostress_to_sentinel_csv(s2_srf_options, illuminant)
```
or you can use the other lower level functions again with ```illuminant = get_well_known_illuminant('identity', wavelength_range)```

**Comment by paolodep36** [comment]
Thank you! now the csv display every values for every sentinel band!

**Comment by gdgenchev** [comment]
Alright, this is great! I am closing this issue.
